### ISSUE TITLE
mybatis-plus逻辑删除

### ISSUE THREAD

**Issue by huangbosbos** [zhangdaiscott/jeecg-boot#112]
版本1.1.0 在实体类中添加@TableLogic
```java
    /**
     * 删除状态（0，正常，1已删除）
     */
    @Excel(name = "删除状态", width = 15,dicCode="del_flag")
    @TableLogic
    private String delFlag;
```
pom.xml
```xml
<mybatis-plus.version>3.1.1</mybatis-plus.version>
...
<!--mybatis plus extension,包含了mybatis plus core -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
            <version>${mybatis-plus.version}</version>
        </dependency>
```
application-dev.yml
```
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:org/jeecg/modules/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型
      id-type: uuid
      # 默认数据库表下划线命名
      table-underline: true
```
