### ISSUE TITLE
nacos分组配置问题

### ISSUE THREAD

**Issue by shiningwhh** [zhangdaiscott/jeecg-boot#2355]
##### 问题描述：
一般开发都是多个环境，nacos可能还会多个项目同时用。
单纯靠命名空间会导致配置过多，所以需要用到分组ID
但目前服务发现中缺少这部分的配置，
同时共享配置目前是注释掉的，而且配置的地方也稍有问题

##### 截图&代码：
主要问题，应在
discovery:
中添加
`group: @config.group@`

其次，共享配置也有些问题
```yaml
     #shared-configs[0]:
          #data-id: ${prefix.name}-common.yaml # 配置文件名-Data Id
          #group: ${config.group}   # 默认为DEFAULT_GROUP
          #refresh: false   # 是否动态刷新，默认为false
```
首先这里是注释的，导致group会进入到默认的DEFAULT_GROUP
其次，打开后格式也稍有不对
临时可修改为以下配置
```yaml
 shared-configs[0]:
          data-id: @prefix.name@.yaml # 配置文件名-Data Id
          group: @config.group@   # 默认为DEFAULT_GROUP
          refresh: false   # 是否动态刷新，默认为false
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by shiningwhh** [comment]
贴一下改完的文件吧
路径：
`jeecg-boot-starter/jeecg-boot-starter-cloud/src/main/resources/bootstrap.yml`

```
spring:
  profiles:
    # 当前激活环境
    active: @profile.name@
  main:
    allow-bean-definition-overriding: true
  cloud:
    #配置Bus id(远程推送事件)
    bus:
      id: ${spring.application.name}:${server.port}
    nacos:
      config:
        # Nacos 认证用户
        username: nacos
        # Nacos 认证密码
        password: nacos
        # 命名空间 常用场景之一是不同环境的配置的区分隔离，例如开发测试环境和生产环境的资源（如配置、服务）隔离等
        namespace: @config.namespace@
        # 配置中心地址
        server-addr: @config.server-addr@
        # 配置对应的分组
        group: @config.group@
        # 配置文件后缀
        file-extension: yaml
        prefix: @prefix.name@
        # 支持多个共享 Data Id 的配置，优先级小于extension-configs,自定义 Data Id 配置 属性是个集合，内部由 Config POJO 组成。Config 有 3 个属性，分别是 dataId, group 以及 refresh
        shared-configs[0]:
          data-id: @prefix.name@.yaml # 配置文件名-Data Id
          group: @config.group@   # 默认为DEFAULT_GROUP
          refresh: false   # 是否动态刷新，默认为false
      discovery:
        namespace: @config.namespace@
        server-addr: @config.server-addr@
        watch:
          enabled: false
        group: @config.group@


```
