### ISSUE TITLE
部署到服务器之后样式丢失

### ISSUE THREAD

**Issue by hellozjf** [zhangdaiscott/jeecg-boot#606]
##### 版本号：

jeecg-boot 2.1.0

##### 问题描述：

我按照[http://jeecg-boot.mydoc.io/?t=345682](http://jeecg-boot.mydoc.io/?t=345682)里面的Jar部署方案

1. 我首先部署后端，没有问题，我通过8080端口访问服务器能够正常打开Jeecg-Boot 后台服务API接口文档
2. 我部署前端，先修改了index.html中的`domianURL`，然后用`npm run build`生成代码，最后将生成的代码放到服务器的nginx上面，nginx的配置文件内容见下面的代码块`nginx.conf`。
3. 我的nginx是使用docker部署的，docker-compose.yml内容见下面的代码块`docker-compose.yml`，然后我使用`docker-compose up -d`启动服务，没有任何错误
4. 我访问8081端口（也就是nginx的端口），发现页面没有样式，但是登陆等其它操作都还是正常的。请参见图1和图2。另外控制台上面没有报任何错误，不过加载`chunk-vendors.6a77598d.js`花了20s。你也可以直接访问`http://aliyun.hellozjf.com:8081`查看效果

希望可以得到帮助

##### 截图&代码：

nginx.conf

```

events {}

http {
    keepalive_timeout   75s;

    server {
        listen       80;
        server_name  aliyun.hellozjf.com;

        gzip on;
        gzip_min_length 1k;
        gzip_comp_level 9;
        gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
        gzip_vary on;
        gzip_disable "MSIE [1-6]\.";

        #后台服务配置，配置了这个location便可以通过http://域名/jeecg-boot/xxxx 访问
        location ^~ /jeecg-boot {
            proxy_pass              http://aliyun.hellozjf.com:8080/jeecg-boot/;
            proxy_set_header        Host aliyun.hellozjf.com;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        #解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            if (!-e $request_filename) {
                rewrite ^(.*)$ /index.html?s=$1 last;
                break;
            }
        }
    }
}
```

docker-compose.yml

```
version: '3'

services:
  ant-design-jeecg-vue:
    image: nginx:1.15.12
    container_name: ant-design-jeecg-vue
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
```

图1

![](https://aliyun.hellozjf.com:7004/uploads/2019/10/10/TIM截图20191010012029.png)

图2

![](https://aliyun.hellozjf.com:7004/uploads/2019/10/10/TIM截图20191010011933.png)

友情提示： 未按格式要求发帖，会直接删掉。
